<?php
// src/templates/tickets/create_ticket.php
// Ensure $departments and $issueTypes are passed to this template
// from the controller.
// Also, ensure Session class is available or user info is passed.
$username = Session::get('username', 'Current User');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Submit New Ticket</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <div class="container">
        <h2>Submit New Ticket</h2>
        <nav>
            <ul>
                <li><a href="index.php?action=dashboard">Dashboard</a></li>
                <li><a href="index.php?action=view_my_tickets">View My Tickets</a></li>
                <li><a href="index.php?action=logout">Logout</a></li>
            </ul>
        </nav>

        <?php if (isset($error)): ?>
            <p style="color:red;"><?php echo htmlspecialchars($error); ?></p>
        <?php endif; ?>
        <?php if (isset($success)): ?>
            <p style="color:green;"><?php echo htmlspecialchars($success); ?></p>
        <?php endif; ?>

        <form action="index.php?action=submit_ticket" method="POST">
            <div>
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" value="<?php echo htmlspecialchars($username); ?>" readonly>
            </div>
            <div>
                <label for="department_id">Department:</label>
                <select id="department_id" name="department_id" required>
                    <option value="">-- Select Department --</option>
                    <?php foreach ($departments as $department): ?>
                        <option value="<?php echo htmlspecialchars($department['id']); ?>">
                            <?php echo htmlspecialchars($department['name']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
                <label for="issue_type_id">Issue Type:</label>
                <select id="issue_type_id" name="issue_type_id" required>
                    <option value="">-- Select Issue Type --</option>
                    <?php foreach ($issueTypes as $issueType): ?>
                        <option value="<?php echo htmlspecialchars($issueType['id']); ?>">
                            <?php echo htmlspecialchars($issueType['name']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
                <label for="comment">Comment (Describe your issue):</label>
                <textarea id="comment" name="comment" rows="5" required></textarea>
            </div>
            <!-- DateTime is auto-generated by DB, Status is defaulted to Pending -->
            <button type="submit">Submit Ticket</button>
        </form>
    </div>
</body>
</html>
